version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "twitter-sentiment-backend"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"